apiVersion: apps/v1
kind: Pod
metadata:
    name: mypod-{{ github.run_id }}
    namespace: default
spec:
    replicas: 2
    selector:
        matchLabels:
            app: my-app
    template:
        metadata:
            labels:
                app: my-app
        spec:
            containers:
                - name: my-app-container
                  image: ghcr.io/ZwaenepoelSander/my-app:<VERSION_TAG>
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 80
